### ISSUE TITLE
Consider switching from GLUT to SFML

### ISSUE THREAD

**Issue by phiresky** [cnlohr/noeuclid#23]
(or something else like SDL)  
GLUT seems to be fairly old, SDL/SFML is common and updated. Should resolve input problems.

**Comment by ArchimedesPi** [comment]
As a matter of interest, why SFML and not SDL?

**Comment by phiresky** [comment]
I have used both, but only for very small things. So the argument is mostly that I liked the SFML syntax better (more c++ish, less global clutter, better to read to me).

**Comment by ArchimedesPi** [comment]
@cnlohr does Mint have problems with SDL? If it doesn't, than shouldn't we
use that, as the game should probably be able to run on your box :)

**Comment by ArchimedesPi** [comment]
I could try porting it to SDL to see how well it works.

**Comment by cnlohr** [comment]
That would be good IMO.  Though SDL is a large framework, I don't think GLUT is very good for supporting this.  I am also frustrated to see just how poor support for SFML is right now.

**Comment by ArchimedesPi** [comment]
Can we use [GLFW](http://www.glfw.org/)?

**Comment by ArchimedesPi** [comment]
Because SDL, after some inspection, has a really C-ish event model, which isn't really the easiest to port into what's already going on.

**Comment by ArchimedesPi** [comment]
SFML would *really* be optimal, it's too bad that it's not working on Mint.

**Comment by cnlohr** [comment]
You know, it does work.  I don't know why I didn't do this earlier.  The package maintainer version is awful, but I tried getting a copy straight from SFML's site and it seems to work great!

Forget SDL.

I now have the sfml branch working well (All I did was link and build against the "official" version).  

Somehow it seems triggers are broken room-to-room, so if someone can look into that, solve it then merge it back to master, I would be very appreciative.

**Comment by ArchimedesPi** [comment]
What was the reason we removed CMake?

**Comment by phiresky** [comment]
I added it because I liked how it mostly automatically finds libraries and generates the build parameters. But in comparison to the makefile it pretty much just changed the syntax and made it harder to find out what was going on. Also it didn't have a Find*.cmake for some things (libtcc) so that was included "manually" anyways.

**Comment by phiresky** [comment]
Also, for me all libraries are directly from the package manager, so they are automatically found by the compiler, without needing fancy Find scripts from cmake..

**Comment by ArchimedesPi** [comment]
Shouldn't this issue be closed now?

**Comment by phiresky** [comment]
master branch is currently still using glut

**Comment by ArchimedesPi** [comment]
as soon as I get my computer running again I'll run it through gdb using
SFML, and see at what point the level switch doesn't work.

**Comment by phiresky** [comment]
The room triggers work fine for me, by the way.

**Comment by ArchimedesPi** [comment]
The room triggers have always been glitchy for me, even with GLEW.

**Comment by cnlohr** [comment]
That's rather strange... I just checked with current mainline and it seems to work well.  If you have time to poke around at that it would be awesome.

**Comment by ArchimedesPi** [comment]
Sometimes it works, but the levels just render wrong, and nothing seems to
go wrong with the C/C++ code in GDB (I usally run noeuclid with a debugger).

**Comment by phiresky** [comment]
Was this always like that? / did you try checking out some older version? (like `git checkout 714e8133ee2cc125a5d3c29e36b3cf1090f8b4e7`)

**Comment by ArchimedesPi** [comment]
It's always been like this, on all of my computers (hp pavilion, and
toshiba chromebook 2, which I couldn't believe could run noeuclid :)
