### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by MrDetonia** [cnlohr/noeuclid#31]
Normally I wouldn't post something like this to an issue page, but I'm not getting anywhere in fixing this.

I'm running Debian (Wheezy) and have a full set of development tools installed (gcc/++, make, etc.), as well as TinyCC 0.9.26, and the required development libraries as detailed in README.md (tcc-dev sfml-dev, and glew-dev). 

Upon running 'make -j' in a clean build environment I get a huge list of errors compiling several objects. A good chunk are failures to acknowledge invalid_argument's existence (not declared, and not a member of std messages), others are failures to acknowledge the existence of certain members of classes in the rest of the code.

Output of 'make -j' is here: https://pastebin.com/3RLvhsNg

Are there more dependencies that have been introduced and are not in the README, some error in the code, or is this a problem at my end?

I'm still looking for a solution, but haven't got anywhere yet.

**Comment by phiresky** [comment]
I'm sorry, I can't reproduce this. I'm not sure about other dependencies, but I just tried from a clean Ubuntu14.04 installation, and it worked. `invalid_argument` should be coming from the [standard library](http://www.cplusplus.com/reference/stdexcept/invalid_argument/). Try adding `<stdexcept>` into line 53 in Common.h.

**Comment by MrDetonia** [comment]
Okay, that fixed the invalid_argument errors. I'm still getting a bunch of complaints about GameMap.h lambda functions, and undeclared class members in noeuclid.cpp though.

**Comment by phiresky** [comment]
Oh yeah those. I wanted to take those out sometime, but didn't find a good way yet.

same errors as the above log?

**Comment by MrDetonia** [comment]
The errors are the same, yes.

**Comment by phiresky** [comment]
The import was missing in TCC.h, too. Could you post another log with the last commit?

**Comment by MrDetonia** [comment]
http://pastebin.com/WZp2AB8i

Does not like <noexcept>. Doing a search for that include file now to check it's not hidden in some obscure place on my filesystem.

**Comment by phiresky** [comment]
my mistake. that shouldn't be noexcept

**Comment by MrDetonia** [comment]
Still getting the same errors after changing both to stdexcept

**Comment by phiresky** [comment]
Mh, I don't see anything wrong in the lambda definitions. I'm guessing it's a bug in your compiler version. Try doing this:

```patch
diff --git a/GameMap.h b/GameMap.h
index c66c1a5..8f12d56 100644
--- a/GameMap.h
+++ b/GameMap.h
@@ -60,7 +60,7 @@ public:
             return bind(JumpSpaceV, p, s, ofs, f1, f2, f3);
         }}, {"RequireRoom", [this](istream& i) -> initfn {
             int room; i>>room;
-            return [this,room]() { rooms[room].begin(); };
+            return [this,room]() { this->rooms[room].begin(); };
         }}
     };
```

**Comment by phiresky** [comment]
Also, even if you fix that you will probably still need a newer version of SFML, as those sf:: errors are from there.

**Comment by MrDetonia** [comment]
Yep, the above fixed the GameMap.h errors. I'm going to see if I can grab a newer version of SFML, or build from source instead of using package manager. Will close if I get it working, cheers.

**Comment by MrDetonia** [comment]
Okay, after doing a much needed upgrade to SFML, GLEW, and udev, I now have a working build. Thanks for the help.
