### ISSUE TITLE
How can i compile this in windows - Question

### ISSUE THREAD

**Issue by TA-MA** [cnlohr/noeuclid#32]

**Comment by phiresky** [comment]
It was *kind of* working on windows at some point (see https://github.com/cnlohr/noeuclid/issues/9#issuecomment-59992458), but there are some things that have to be fixed in order for it to work correctly. So sorry, without modifications that won't work currently.

**Comment by phiresky** [comment]
Closing this, there is already https://github.com/cnlohr/noeuclid/issues/5 for further discussion
