### ISSUE TITLE
Mouse movement is not picked up

### ISSUE THREAD

**Issue by ghost** [cnlohr/noeuclid#35]
Mouse movement is not picked up

**Comment by cnlohr** [comment]
sorry, I'm going to need some more platform details, etc.  Does it at least capture mouse movement?

**Comment by ayunami2000** [comment]
windows 10

**Comment by ayunami2000** [comment]
it seems to just hide the mouse, but it doesnt lock it in the application or anything. it does not react to moving the mouse at all. using windows 10 and msys as mentioned in readme.md

**Comment by cnlohr** [comment]
oh man that's weird... I wonder if it just rendered one frame and stopped.  I'm glad you found a solution. I need to close this anyway.
