### ISSUE TITLE
Room 9 doesn't raise dirt blocks from lava

### ISSUE THREAD

**Issue by bluebear94** [cnlohr/noeuclid#43]
Using commit 8cdd08a0, built on Ubuntu 17.04.

**Comment by cnlohr** [comment]
what?  Well.  #1: Congratulations on getting the monstrosity to work.  #2: I've NEVER seen a bug like that.  Can you get video?

**Comment by bluebear94** [comment]
1. I just symlinked `/usr/lib/x86_64-linux-gnu/tcc/libtcc1.a` to `/usr/lib/x86_64-linux-gnu/libtcc.a`.
2. I don't really feel like going through all the levels again, sorry.

**Comment by cnlohr** [comment]
You can edit the main script to set the level number at startup.  Also, I believe there's a key you can press on the keyboard to advance levels.

**Comment by TNian145** [comment]
![room9](https://user-images.githubusercontent.com/14333613/30598276-00d67278-9d62-11e7-8285-24015a9f4313.png)

**Comment by cnlohr** [comment]
I cannot reproduce this problem.

**Comment by TNian145** [comment]
TNian145@f33d2202daa5c26901a7b716a362b027cfb3c959 fixes the issue for me.
@bluebear94 can you try this commit to see if it fixes the issue for you too?
