### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by karlygeeky** [cnlohr/noeuclid#50]
What are the license terms for the game? Open source projects usually have an open source license.

helpful links:
https://opensource.org/licenses
https://choosealicense.com/

**Comment by karlygeeky** [comment]
If you don't want to copyright the game consider using [the Unlicense](http://unlicense.org/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by cnlohr** [comment]
Ah, it's actually under the New BSD license, I just totally forgot to tell github that.  It's fixed now. Also, your icon.  You've found a color that confuses my screen.

**Comment by cnlohr** [comment]
P.S. @karlygeeky were you thinking about doing something with this?

**Comment by cnlohr** [comment]
Just to close the loop for anyone looking at this: The TL;DR of the BSD license this is under is anyone is free to take this or any basis thereof that is not already under a competing license and make a closed-source commercial game of their own as long as somewhere credit's given.
