### ISSUE TITLE
Lubuntu VirtualBox--tinycc compile location

### ISSUE THREAD

**Issue by ayunami2000** [cnlohr/noeuclid#53]
the game cant find tinycc, it compiled to /usr/local/lib/tcc but the game only looks in /usr/lib/x86_64-linux-gnu/tcc
i was able to create a soft link between the folders to fix the issue.

**Comment by cnlohr** [comment]
Creating the soft link should work.  Did you have any further issues?

**Comment by ayunami2000** [comment]
Nope, the soft link seemed to do the trick.
